### ISSUE TITLE
[feature] idea: Multiple review files

### ISSUE THREAD

**Issue by fmalcher** [d-koppenhagen/vscode-code-review#1]
- location and of the review file should be configurable via config file (e.g. use default name when no config is present, use config value if set)
- maintain multiple review files in parallel
- option in the context menu to add to a specific review file
- all review files are registered in the config file

**Comment by d-koppenhagen** [comment]
What’s the use case for multiple files? I just think about if it makes sense? 🤔 
But yes: let users configure where the files is stored and the name of the file should be possible in the future via options.

About multiple fils: I am currently working on a webview form for adding the comments and further information (short title, priority, etc.).
Probably a selection of the target review file could fit into it.

**Comment by fmalcher** [comment]
I'm not really sure, but I thought it to be clever to have multiple collections of review stuff on different dates or for different people.
I imagine that the csv file will be committed with the repo, and later we do another review with the same code – in a separate file.

However, does not have any higher priority 😅

**Comment by d-koppenhagen** [comment]
I think this special case can be achieved by just changing the review file name within the settings.
One one review is finished, switch the fine name in the settings and a new file is created. 
When you want to edit the first file, you need just to switch back the name in the options and the file is used and comments will be appended.
I will close this issue as it’s solvable and probably very special.
