### ISSUE TITLE
[bug]Can't add a new note

### ISSUE THREAD

**Issue by Neightly** [d-koppenhagen/vscode-code-review#103]
# 🐞 Bug report

## Description

select codes and click `Code Review: Add Note`, it has no effect.

## Error message

<pre><code>
ENOENT: no such file or directory, open '\Users\Administrator\.vscode\extensions\d-koppenhagen.vscode-code-review-1.24.1\dist\webview.html'
</code></pre>

## 🌍 Your Environment

<pre><code>
real path of the html file is located at `C:\Users\Administrator\.vscode\extensions\d-koppenhagen.vscode-code-review-1.24.1\dist\webview.html`, but I'm NOT working on disk C.
</code></pre>

**Comment by Neightly** [comment]
It seems that disk drive letter is lost when obtaining the absolute path.
when vscode located at D:\ or E:\ , it could not found the right path.

**Comment by d-koppenhagen** [comment]
Thanks for opening this issue. I will try to fix it and check this out.
As I am working on a Mac, it can be that I need further support

**Comment by d-koppenhagen** [comment]
@michelcaradec are you working on windows? Could you help me out here?

**Comment by michelcaradec** [comment]
> @michelcaradec are you working on windows? Could you help me out here?

@d-koppenhagen I'm on Mac at home, and Linux at work, and unfortunately no access to a PC. 
Anyway, we need a multi-drives setup, with system drive not being the C one. 
The only solution I see is to install a virtual machine with an evaluation version of Windows and make our own installation.

**Comment by d-koppenhagen** [comment]
Hey, I was able to reproduce and fix the problem by setting up a virtual machine for testing purpose.
See here: https://recordit.co/PQzQiPXG7p

Please checkout version `1.27.1` which fixed the bug
