### ISSUE TITLE
[feature] Code context in the code review comment page

### ISSUE THREAD

**Issue by HugoCunha** [d-koppenhagen/vscode-code-review#104]
# 🧩 Feature

## Description 

It would be nice to have a quote box in the 'Edit code review comment page' with the code referring to that issue. It would be much easier to have a context about the referred issue.
An extra feature would be being able to see the code diff in that box after the review.

Thank you for the great work. 👍

**Comment by d-koppenhagen** [comment]
Hey @HugoCunha when editing a previous made comment, the related code should be highlighted in the related file so that the context is visible.
Is there probably a bug with the highlighting? Or I just didn't understand your exact expectation.

**Comment by d-koppenhagen** [comment]
I will close this issue for now. Feel free to re-open it, when it's still relevant and describe the feature request a bit more in detail.
Thanks!
