### ISSUE TITLE
[feature] Icon indicating a code review comment

### ISSUE THREAD

**Issue by HugoCunha** [d-koppenhagen/vscode-code-review#105]
# 🧩 Feature

## Description

It would be extremely useful to have an icon indicating lines of code that have an associated review comment.

As an example, consider some comment referring to the lines 40 to 42. An icon in the beginning of the line 40 could indicate that there is a comment or issue related with that part of the code.

**Comment by d-koppenhagen** [comment]
Thanks for your suggestion. The feature has been implemented in version `1.27.0`. Give it a try.
