### ISSUE TITLE
[bug] Support multi-root workspace

### ISSUE THREAD

**Issue by girivs82** [d-koppenhagen/vscode-code-review#106]
# 🐞 Bug report

## Description

 Currently, code-review.csv is generated in the first root of a multi-root workspace

## Reproduction

 Simply have more than one root in your workspace, you will notice the code-review.csv will be generated only in the first workspace root.

## Error message

<pre><code>
 
</code></pre>

## 🌍 Your Environment

<pre><code>
 
Vscode MacOs running remote ssh to linux
</code></pre>

**Comment by AlexandreMarkus** [comment]
+1

**Comment by d-koppenhagen** [comment]
@girivs82 please checkout version `1.26.0` it should support multi-root workspaces now.
@AlexandreMarkus thanks for this very helpful links as I didn't had any clue about how to implement it before 😄

**Comment by girivs82** [comment]
thanks! I'll take a look today or tomorrow.

**Comment by AlexandreMarkus** [comment]
> @girivs82 please checkout version `1.26.0` it should support multi-root workspaces now.
> @AlexandreMarkus thanks for this very helpful links as I didn't had any clue about how to implement it before 😄

Thank you, I confirm it is working well with multi-root!!! Great job!!

**Comment by girivs82** [comment]
LGTM! Thanks to both @d-koppenhagen and @AlexandreMarkus for quick implementation and support!
