### ISSUE TITLE
[bug] Cannot access comment explorer

### ISSUE THREAD

**Issue by girivs82** [d-koppenhagen/vscode-code-review#107]
# 🐞 Bug report

## Description

 Cannot access the code review comment explorer at all

## Reproduction

 When running in remote ssh mode, adding a note works and csv is generated. However, this csv is not detected by the extension and the code review comment explorer pane does not show up at all. Not sure if this is related to running in a remove ssh environment or not. It works when used natively on a workspace on my mac without remote ssh.

## Error message

<pre><code>
 
</code></pre>

## 🌍 Your Environment

<pre><code>
 
Vscode macOS running remote ssh on linux
</code></pre>

**Comment by d-koppenhagen** [comment]
@girivs82 can you please send me the vscode version you are running?
```bash
code -v
```

**Comment by girivs82** [comment]
Sure,

Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

For the remote ssh vscode-server running in linux, I saw this message:
[09:58:00.602] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server

**Comment by girivs82** [comment]
Not sure what happened, but all of a sudden, it started showing up from today. I tried to recall what changed from last time and the only thing I can think of is adding vscode path to .zprofile so that I can run code from command line. to be able to run code -v as you requested.

Do you think this could be the reason? In any case, I'm closing this since it's working now. Sorry for the bother.

**Comment by girivs82** [comment]
Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.6.0

[Shankar Giri V - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=15r2mi)	[15r2mi]

On June 24, 2021 at 18:33 GMT, Danny Koppenhagen ***@***.***> wrote:

***@***.***(https://github.com/girivs82) can you please send me the vscode version you are running?
code -v
