### ISSUE TITLE
[bug] Error when trying to create code review file

### ISSUE THREAD

**Issue by kvistgaard** [d-koppenhagen/vscode-code-review#108]
When selecting "Code Review: Add Note", I get

![image](https://user-images.githubusercontent.com/7572721/126312014-ca6cc634-a8d3-4649-be2a-c0638670d105.png)
 
Indeed, files cannot be created in that directory but I why is it trying to create there by default? I went through the settings, expectations it will be in commonly used. It wasn't so I continued and still cound't find it, although, considering how many they are, I might've missed something.

**Comment by d-koppenhagen** [comment]
Hey @kvistgaard , I made some changes in the latest version (`1.26.0`) to support multi-root workspaces. I made also some refactorings and implemented additional watchers for defining the workspaceRoot new, once the active workspace changes. However, can you please try out if it works with the latest version?
I think for some reason the root path to the current active workspace could be determined (which is requested here: https://github.com/d-koppenhagen/vscode-code-review/blob/master/src/extension.ts#L11).
Can you check also the permissions for r/w to on your specific workspace?

**Comment by d-koppenhagen** [comment]
I will close this issue for now. Feel free to re-open it, when the error still occurs.
Thanks.

**Comment by kvistgaard** [comment]
With 1.27.3 I have exactly the same error.

**Comment by d-koppenhagen** [comment]
Thanks for your response. I was able to reproduce the error now I think. The problem occurs when the workspace root path cannot be retrieved. This happens for example when you right click on a file somewhere on your disk and then "Open with Visual Studio Code" or when selecting a single file (not an enclosing directory) via the "open" menu (see screenshot). In such cases VSCode works as a simple file editor without any workspace context.
![Screenshot 2021-08-16 at 18 55 10](https://user-images.githubusercontent.com/4279702/129600822-2aae7ef8-65a9-486c-8012-5a442cce21e9.png)

I am on it :)

**Comment by d-koppenhagen** [comment]
Please try out version `1.27.4`. If the error still occurs, can you please note step-by-step, how you are producing the situation (How do you open VSCode (Context Menu, Menu)? What file / directory do you open? What VSCode Version are you running? War you working via a remote Host connection?, etc...

**Comment by kvistgaard** [comment]
Not it finally works! Thanks!

**Comment by d-koppenhagen** [comment]
Great. Your welcome!
