### ISSUE TITLE
All Lines from 0 to end of code selected highlighted for comment

### ISSUE THREAD

**Issue by sjwar455** [d-koppenhagen/vscode-code-review#110]
When viewing/updating a comment via the Code Review: Comment Explorer side bar, all lines from 0 to end of selected code are highlighted. 

Scenario: 
1. select lines 100 - 105 for comment
2. create comment & click update
3. Select comment in Code Review: Comment Explorer side bar
4. All lines from line 0 to 105 are highlighted 
5. Sad face

Versions Affected: 
1.27.0
1.27.1
1.27.2

Extra: 
* does not impact position reported in exported html code review

**Comment by d-koppenhagen** [comment]
Thanks for reporting this issue. It should be solved with version `1.27.3`.
