### ISSUE TITLE
[feature] Allow to edit the note from the source 

### ISSUE THREAD

**Issue by ricardodeazambuja** [d-koppenhagen/vscode-code-review#111]
# 🧩 Feature
Allow to edit the note from the source code where it was applied (instead of using the code review tab)

## Description
Currently, the only way I can edit a note is by using the code review tab. It would be nice if we could edit the note when visualizing it directly in the source code (hovering the mouse over the dot or right-click the note icon).

**Comment by d-koppenhagen** [comment]
I am on it. I think I will switch from simply decorating the relevant parts inline to a `CodeLensProvider` implementation that allows direct linking to commands

**Comment by d-koppenhagen** [comment]
please checkout version `1.28.0` containing the implementation for this feature.
