### ISSUE TITLE
[bug] Duplicate comment icons

### ISSUE THREAD

**Issue by bluenick2k17** [d-koppenhagen/vscode-code-review#113]
# 🐞 Bug report

## Description

I see a newer feature of the tool is that the comments are displayed in-line. Looks cool! Although I noticed a weird bug, it displays three comment icons instead of one. And every time I click the "Code Review:" text and click back into the file, it adds two more.
![image](https://user-images.githubusercontent.com/50033488/131033485-8324fc67-af33-4236-8b47-ee6f3722d90a.png)
![image](https://user-images.githubusercontent.com/50033488/131033520-4612f43a-018e-406c-988b-4782d2922399.png)

Could it also be explored to put the comment icon at the end of any given line instead of wherever the comment ends? That would be quite helpful since those comment icons can interrupt the line of code I'm reading.

## Reproduction

- Open a file with some code
- Create a new code review comment
- Click on the "Code Review:" text above the code you just highlighted
- Click back into the file
- Repeat as desired

## 🌍 Your Environment

<pre><code>
Using Windows 10 to connect to a linux server via Remote SSH. However, was able to reproduce the same/similar issue without this remote connection.
</code></pre>

**Comment by d-koppenhagen** [comment]
I implemented the icon placement fix (at the end of the line) with version `1.29.1`. please check it out. When you can confirm that the bug doesn't exists anymore, I will close this issue.

**Comment by bluenick2k17** [comment]
Thanks for the icon fix! Can confirm I don't see that the bug in 1.29.1.
