### ISSUE TITLE
[bug] Does not work on Nixos

### ISSUE THREAD

**Issue by drupol** [d-koppenhagen/vscode-code-review#116]
# 🐞 Bug report

## Description

Hi,

I'd like to use this amazing extension on my Linux system based on Nixos.
When I try to create a note, it says that it is not possible to create the CSV file.

This is normal because on Nixos, all the software are installed in /nix/store and it's not possible - as a user - to write in those directories.

Do you think it would be possible to save the CSV file somewhere ? Or at least let users customize where to save those files?

Thanks.

**Comment by d-koppenhagen** [comment]
Hey, thanks for opening this issue. Probably I can add a `.vscode/settings.json` option for defining the path where to store the file.

**Comment by drupol** [comment]
Yeah, IMHO it should be by default in the project directory... something like: `.vscode/code-review/`
