### ISSUE TITLE
[feature] Make description optional

### ISSUE THREAD

**Issue by inconspicuous-username** [d-koppenhagen/vscode-code-review#129]
# 🧩 Feature
Make the description field optional
## Description
During code reviews I regularly add short notes as I read the code, hinting future me that something is going there.
This is super helpful as the title of the note is shown directly in the code.

The issue with that approach is that the description is a required field.
Currently my work around is just hitting my space bar to bypass the mandatory description.

It would be nice if the description field can be left empty when trying to make a not.

Thanks in advance, and thanks for the awesome tool!

**Comment by d-koppenhagen** [comment]
all-contributors add @inconspicuous-username for ideas

**Comment by d-koppenhagen** [comment]
@all-contributors add @inconspicuous-username for ideas
