### ISSUE TITLE
Setting default template for HTML export requires restart

### ISSUE THREAD

**Issue by brandonchupp** [d-koppenhagen/vscode-code-review#136]
# 🐞 Bug report

## Description

Any update to default template for HTML export (`code-review.defaultTemplatePath`) requires a VSCode restart.

## Reproduction

* Set or modify the `code-review.defaultTemplatePath` value in settings.
* Perform an HTML default export.
* Your new template will not be used.
* Restart VSCode.
* Perform an HTML default export.
* Your new template is used.

## Error message

N/A

**Comment by d-koppenhagen** [comment]
I assume the same happens for markdown right?

**Comment by brandonchupp** [comment]
> I assume the same happens for markdown right?

Yes, it does. I'll have a fix for both shortly.

**Comment by d-koppenhagen** [comment]
closed by #136
