### ISSUE TITLE
[bug] No priority icon is shown in the list for notes with long description

### ISSUE THREAD

**Issue by avernan** [d-koppenhagen/vscode-code-review#142]
# 🐞 Bug report

## Description

When setting a note with a long description, the "Code Review" pane that shows all notes does not show the colored icon for priority for the long note.
![image](https://user-images.githubusercontent.com/9851882/194542606-a0173cb2-dab9-4fc7-b24d-f0e7920925dc.png)

The priority is correctly stored in the CSV file and populated in the "Update note" window

Edit to add: The priority is also missing when exporting to HTML with the default template

## Reproduction

Create a note with 2+ paragraph of lorem ipsum

## 🌍 Your Environment

Happening on Windows 10

**Comment by d-koppenhagen** [comment]
I noticed, that this issue also appears when having short descriptions but linebreaks. e.g. the following description input leads to this error:

```
Lorem
Ipsum
```
