### ISSUE TITLE
[bug] Display issue in the side panel when notes have descriptions including line-breaks

### ISSUE THREAD

**Issue by avernan** [d-koppenhagen/vscode-code-review#143]
# 🐞 Bug report

## Description

When a note's description includes multiple lines, the side panel with the list of all notes attempts to render the descriptions including the linebreaks
![image](https://user-images.githubusercontent.com/9851882/194558521-256bb8c0-7c66-49bd-a441-6e4fe609dc6e.png)

## 🌍 Your Environment

Windows 10. I didn't have this issue before, so I am wondering if it might be related to changes in VSCode. I did update to VSCode 1.72? at some point in the last few days (not sure if the two events happened at the same time).

**Comment by d-koppenhagen** [comment]
closed by #145
