### ISSUE TITLE
[feature] Add the "category" option for each note

### ISSUE THREAD

**Issue by alexeystrakh** [d-koppenhagen/vscode-code-review#20]
# 🧩 Feature

## Description

Add the ability to specific categories such as Performance, Maintainability, Reliability, Architecture etc. Also would be nice to configure custom fields, I'm thinking about  Severity, Area (client, server, etc).

**Comment by d-koppenhagen** [comment]
makes totally sense. A configurable opion via vscode config.
I will think about more default categories such as:

- Best Practices
- Code-Style

**Comment by alexeystrakh** [comment]
Configurable is the best 👏

**Comment by d-koppenhagen** [comment]
Checkout version 1.3.0. You can configure the categories by [`code-review.categories`](https://github.com/d-koppenhagen/vscode-code-review#extension-settings)
