### ISSUE TITLE
[bug] Clickable links in default template

### ISSUE THREAD

**Issue by alexeystrakh** [d-koppenhagen/vscode-code-review#22]
# 🧩 Feature

## Description

Once the template is generated, the links are not clickable and don't include line numbers. It would be nice to have an ability to open files locally (let's say in the VSCore) or even specify base url and line number format to open specific link right in the repo, e.g. I specify in settings that my link format is below:

`https://github.com/alexeystrakh/Xamarin.Forms.Doodle/blob/master/{File}#L{LineNumber}`

And the link `Xamarin.Forms.Doodle.DoodleApp.Android/MainActivity.cs` at `line 13` will be generated as:

`https://github.com/alexeystrakh/Xamarin.Forms.Doodle/blob/master/Xamarin.Forms.Doodle.DoodleApp.Android/MainActivity.cs#L13`

**Comment by d-koppenhagen** [comment]
The link should be included and work once [baseUrl] is configured: https://github.com/d-koppenhagen/vscode-code-review#extension-settings

So it seems more like a bug. Can you tell me the configuration settings and attach the content of the generated `*.csv` file?

**Comment by alexeystrakh** [comment]
I didn't know about the setting but know I set it and neither cvs nor html report contains a valid link, just a relative path.
