### ISSUE TITLE
[bug] Line number included into CVS is -1 from the original number

### ISSUE THREAD

**Issue by alexeystrakh** [d-koppenhagen/vscode-code-review#23]
# 🐞 Bug report

## Description

Select line in code and hit hotkey to add the comment, the line in the csv report is -1 from the original value.

## Reproduction

1. select line of code
2. hit the hotkey to enter a comment
3. enter comment

Expect result: line number in the report corresponds to the line in the code
Actual result: actual line number is -1 from the original value

**Comment by d-koppenhagen** [comment]
Oh yes, I assume vscode delivers the index, not the actual line number. I'm on it
