### ISSUE TITLE
[feature] include related code in reports

### ISSUE THREAD

**Issue by d-koppenhagen** [d-koppenhagen/vscode-code-review#24]
# 🧩 Feature

## Description

Read code per file from the `lines` property (can be an array when joined with `|`).

Include a block to optionally inject the code in the report: 

### HTML

The default template should include this:

```html
<pre><code>...</code></pre>
```

 ### Github/Gitlab

<pre><code>
```
...
```
</code></pre>

### JIRA

```text
{code}
...
{code}
```

### JSON

```json
{
  ...,
  sources: [
    ...
  ]
}
```

- [x] Code in HTML Report
- [x] Code in JIRA report
- [x] Code in Github/Gitlab report
- [x] Code in JSON
- [x] Configuration Option, to include code in reports

**Comment by Ben07** [comment]
how to use this feature?
Does this mean that there are selected code snippets in the report？
