### ISSUE TITLE
[bug]Gitlab Highlight the selected line

### ISSUE THREAD

**Issue by hockor** [d-koppenhagen/vscode-code-review#25]
# 🐞 Bug report

## Description

Thank you very much for the plugin,but I have some doubts in use
In gitllab, you cannot use #L94-L130 to highlight these lines, only #L94-130.

for example 

not work : [https://gitlab.com/gitlab-org/gitlab-foss/-/blob/b0b4a0cc37e1cb2794e267e06ac47143085a0175/app/models/user.rb#L90-L136](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/b0b4a0cc37e1cb2794e267e06ac47143085a0175/app/models/user.rb#L90-L136)

good work : [https://gitlab.com/gitlab-org/gitlab-foss/-/blob/b0b4a0cc37e1cb2794e267e06ac47143085a0175/app/models/user.rb#L90-136](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/b0b4a0cc37e1cb2794e267e06ac47143085a0175/app/models/user.rb#L90-136)

but in  code-review.gitlab.csv 

- file: /src/api/index.js  ： https://gitlab.com/xxxx/index.js#L116-L124

**Comment by d-koppenhagen** [comment]
you are right. This currently hardcoded. I think the best way is to provide a config option where you can customise such part (that will fit also for non GitHub or GitLab instances probably).
See: #26

**Comment by hockor** [comment]
yes .Thank you for your reply and look forward to this feature

**Comment by d-koppenhagen** [comment]
fixed and released. Check our version 1.6.0.

You need to configure `code-review.customUrl` like this:

```
https://gitlab.com/gitlab-org/gitlab-foss/-/blob/{sha}/{file}#L{start}-{end}
```

**Comment by hockor** [comment]
great ! thanks
