### ISSUE TITLE
[feature] Ordering code comments by line number, after grouping.

### ISSUE THREAD

**Issue by bluenick2k17** [d-koppenhagen/vscode-code-review#38]
# 🧩 Feature
Ordering code comments by line number, after grouping
## Description
Currently, if I want to group by file name, the comments are ordered by which review comment was completed first. I think a togglable feature (especially when you are grouping by file name) that would be very useful would be to have the comments display in line order since in file name grouping, the order (in my eyes) doesn't matter as much. Theoretically, you could also order by things like priority as well although for a first go at it, this is the most important use case I see.

You could do the ordering like so (takes the first ordering that is successful):
1. Earlier of the beginning line numbers
2. Later of the ending line numbers (If I have two comments starting at the same position, I would probably want to see the longer code block first since it may be over-arching, but this is up to interpretation)
3. Earlier of the starting column (this assumes they are on the same line)
4. Earlier of the ending column
5. At this point it's kind of arbitrary in my opinion

I don't know if logic that complex is needed, but I figured I'd offer it just in case. Looking forward to your feedback!
 A clear and concise description of the feature

**Comment by d-koppenhagen** [comment]
Makes totally sense for file grouping.
I am just thinking how to sort multiple ranges related to one comment.
It's currently possible as well to create a comment for e.g. lines 10-13 AND 18-20 by pressing the shift key when selecting the line ranges.
How can it be sorted the best way when ether is another comment that's maybe covering lines 14-19?
I think in such case I would prefer to always just look at the first line selection in a comment and order by this one.
What do you think?

Maybe an example how sort could look like:

A files contains the following selections:

- `5:3-8:2`
- `4:2-6:7|9:0-12:8`
- `8:6-9:3`
- `10:5-10:12|7:2-11:3` (I have to check if this case exists. If yes the selections has to be ordered within itself first)
- `3:2-14:6`
- `4:5-15:0`

(I hope it covers all the cases)

The result should be:
- `3:2-14:6`
- `4:5-15:0` (as it has a bigger range then the next one and the position inside the line will be ignored)
- `4:2-6:7|9:0-12:8`
- `5:3-8:2`
- `10:5-10:12|7:2-11:3` (as the second selection is the next when sorting - if that case exists)
- `8:6-9:3`

Am I wrong? Would you order something differently?

**Comment by bluenick2k17** [comment]
This sorting makes a lot of sense to me! Ordering by the first line makes sense when it comes to dealing with overlapping ranges. I also agree with how you’d handle those multiple code block sections.

Thanks for putting those ranges in an example! It helped a lot to understand how things would be ordered.

**Comment by d-koppenhagen** [comment]
Great. So now it's ready for implementation. I will find some time probably the next days

**Comment by d-koppenhagen** [comment]
Here it is! Version `1.14.0` contains this feature. Thanks for reporting it.

**Comment by bluenick2k17** [comment]
Awesome, verified it works as I expect it to! Thanks for the feature.
