### ISSUE TITLE
[bug] Off by one line error in code output

### ISSUE THREAD

**Issue by bluenick2k17** [d-koppenhagen/vscode-code-review#49]
# 🐞 Bug report

## Description

In the newest version of the extension, the code output in the report is not printing the first line of the selection.
## Reproduction

Add a code review comment where you only highlight a single line (examples that I had: 3:0-3:34, 4:0-4:20) and the code output will not be generated in the report. Change the line number at the end to the next line down (4:0 and 5:0) and they print fine. I also just found that doing a two line highlight was only producing output for the second line and not the first line. This seems to be replicated over all of my review comments.
## Error message

<pre><code>
 
none
</code></pre>

## 🌍 Your Environment

<pre><code>
 
Just updated to 1.17.0
</code></pre>

**Comment by bluenick2k17** [comment]
Just confirmed that the off by one error does not happen in 1.14.0, but does in 1.17.0.

**Comment by d-koppenhagen** [comment]
Thanks for reporting it. It was introduced by a refactoring. 
I just fixed it with version 1.17.1.
