### ISSUE TITLE
[bug] Updating VS code extension overrides custom categories specified in settings

### ISSUE THREAD

**Issue by bluenick2k17** [d-koppenhagen/vscode-code-review#50]
# 🐞 Bug report

## Description

 Updating VS code extension overrides custom categories specified in settings.

## Reproduction

 Add one or more custom categories, or remove some, and then update the extension, and the categories go back to the ones that ship with the extension by default.

## Error message

<pre><code>
 none
</code></pre>

## 🌍 Your Environment

<pre><code>
 Version 1.17.0
</code></pre>

**Comment by d-koppenhagen** [comment]
Hmm this seems a bit odd. I think there wasn't a change touching this. The settings key is still the same.
So when you add your custom categories again to the plugin and re-install it, will the customs categories still be there?
I tried to reproduce the problem but without any success.

**Comment by bluenick2k17** [comment]
It was specifically when I updated from 1.14.0 to 1.17.0 I believe, although then I went from 1.17.0 back to 1.14.0 and it saved my categories so I'm not completely sure. I can also try again to reproduce it if I get the time.

**Comment by d-koppenhagen** [comment]
jep, that would be great. 
Please save and copy/paste the config before and after here in this issue when it still occurs.
Btw. 1.17.1 has been released just now.

**Comment by bluenick2k17** [comment]
Hm I just tried the upgrade again (to 1.17.1) and it seems to work fine. It's also possible I may just have been confused with the workspace config because _that_ is default. What I'll do is close this and if I find it happening I will open another issue.

PS thanks for the quick fix on the off by one error! It works like a charm now.

**Comment by d-koppenhagen** [comment]
Yes that sounds good.
