### ISSUE TITLE
[bug] Review content disappears if you leave the editor screen

### ISSUE THREAD

**Issue by tillig** [d-koppenhagen/vscode-code-review#53]
# 🐞 Bug report

## Description

If you start a review comment and click a different tab to go check something out, coming back to the review comment has cleared out all the comment content previously written.

## Reproduction

1. Open a folder with some code to review.
2. Double-click to open a file in the file explorer.
3. Hit ctrl+shift+N to start a new review comment.
4. Type something in the 'title' field.
5. Double-click another file in the file explorer, like you're going to check something while you're reviewing.
6. The new file will open in the same editor pane as the review comment in progress.
7. Click the tab with the review comment to go back and finish filling it out. The content previously entered in the 'title' field is gone; the form is reset.

## Error message

None.

## 🌍 Your Environment

- MacOS 10.15.6
- VS Code 1.48.2
- vscode-code-review 1.19.0

**Comment by d-koppenhagen** [comment]
Thanks for reporting it. The fix has landed in version `1.19.1`.
