### ISSUE TITLE
[bug] Off by one error on HTML report generation

### ISSUE THREAD

**Issue by bluenick2k17** [d-koppenhagen/vscode-code-review#57]
# 🐞 Bug report

## Description
When I select lines 3:0-3:44 for example, it shows up in the CSV as 3:0-3:44 but the report generates it as if I selected the whole 2:0 line. I have also seen where multi-line selections shift up one line when generating the code snippet.

## Reproduction
Create a file that contains multiple lines, select a line with text above it (I selected the whole line of text if that helps), and then produce an HTML report with code snippets enabled.

## Error message

<pre><code>
none
</code></pre>

## 🌍 Your Environment

Running extension version 1.19.2

**Comment by bluenick2k17** [comment]
Also just rolled back to 1.19.1 and can confirm that it works fine there :) so I'm able to keep working off that for now.

**Comment by d-koppenhagen** [comment]
please check out version 1.19.3 which will fix this issue. This was caused a a side effect of #56

**Comment by bluenick2k17** [comment]
Thank you for promptly addressing this! I can confirm 1.19.3 fixes the issue.
