### ISSUE TITLE
[feature] Productivity features

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#69]
# 🧩 Feature

## Description

Having the ability to type a note without leaving your hands from the keyboard can make you more efficient while reviewing some code.

Here are my suggestions:

1. Give **focus** to the comment edit zone so you can start typing immediately after the the note appears.
2. Add some **keyboard shortcut** such as:
    - <kbd>Ctrl</kbd> + <kbd>Return</kbd> to validate the note.
    - <kbd>Ctrl</kbd> + <kbd>Esc</kbd> to cancel the note.

If the feature request is approved, I propose to do the implementation (which is already done on my local repository actually ;-)).

**Comment by d-koppenhagen** [comment]
Sounds great! I would love to receive the PR 🤩
