### ISSUE TITLE
[feature] Modify Code Selection

### ISSUE THREAD

**Issue by tigerbeard** [d-koppenhagen/vscode-code-review#72]
# 🧩 Feature

Modify Code Selection

## Description
It would be nice to be able to edit the code line/char fields from the `Edit code review comment` pane.

Currently, the ways to change the line/char fields on a comment are either create a new comment with the correct selection and delete the old one, or manually edit the CSV file.

**Comment by michelcaradec** [comment]
I just submitted a pull request (#73) related to this feature request.
