### ISSUE TITLE
[feature] Private/public comments

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#84]
# 🧩 Feature

## Description

When working on a review, it can be handy to be able to make some personal annotations, especially during the "discovery" of the code.
Those annotations are not aimed to be sent to the developer. They are more here to support the review process.

I suggest to add a "private/public" property to the comment.

A private comment will follow the following rules: 
- Excluded from the export (but we can add a setting to force inclusion in the export).
- Appear in the tree-view in "grey" (i.e. a bit less visible than public comments).

This feature will require an extra property ("private"), which addition is now made easier with #79 .

**Comment by d-koppenhagen** [comment]
Sounds great to me.
Probably the UX for the appearance of private comment items in the tree view would be even better with an appropriate icon and hover title?
I think the API for [TreeItem](https://code.visualstudio.com/api/references/vscode-api#TreeItem) supports already a `description` value which is less prominent compared to the `label`.
