### ISSUE TITLE
Can't Installed Extension on version 1.27.2 (1.27.2) 

### ISSUE THREAD

**Issue by beyondverage0908** [d-koppenhagen/vscode-code-review#86]
description: Can't Installed Extension on version 1.27.2 (1.27.2) 
system: mac
report reason: Unable to install Extension 'd-koppenhagen.vscode-code-review-1.21.0' as it is not compatible with Code '1.27.2'.

**Comment by d-koppenhagen** [comment]
please update your vscode to the latest version or at least version `1.50.0` since this extension has a dependency to this version:
https://github.com/d-koppenhagen/vscode-code-review/blob/master/package.json#L19
