### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by beyondverage0908** [d-koppenhagen/vscode-code-review#87]
# 🐞 Bug report

## Description

Add code review comment Panel blank，can't input, no cursor. 

## Reproduction

1. selected code
2. right click
3. Code Review:Add Node
4. vscode right panel blank

## Error message

no error message

## 🌍 Your Environment

system version: windows10 
vscode version：1.52.1

**Comment by d-koppenhagen** [comment]
Sorry I couldn't verify this until now.
Can you please uninstall and re-install the plugin and try it again?
Was there already a `code-review.csv` file present in the project? Or is the file created?

![Screenshot 2021-01-15 at 07 18 31](https://user-images.githubusercontent.com/4279702/104689007-13e11000-5702-11eb-8ac4-4bdf9f4b5d90.png)

If yes: can you please paste the file contents here?
Can you also check the VSCode log for any error? (Menu: "View" => "Output"). Select "Log (Window)" on the right.

**Comment by beyondverage0908** [comment]
1. I try to uninstall and re-install the plugin, but it still can't work
2. ![image](https://user-images.githubusercontent.com/11870736/105446219-9e9aaf80-5cac-11eb-852a-28a057f57332.png)
![image](https://user-images.githubusercontent.com/11870736/105445840-dd7c3580-5cab-11eb-96dc-b7c7e500d9be.png)
when I click "Code Review: add note", vscode is created `code-review.csv` file. paste contents on below
`sha,filename,url,lines,title,comment,priority,category,additional,id,private`
3. I also check the VSCode log, but there was no any output

**Comment by d-koppenhagen** [comment]
@beyondverage0908 unfortunately I am not able to reproduce this behaviour.
It could be some problem with your vscode installation but I am really not sure.

can you try to run vscode with administrator permissions and try the same things? Just to check if there is some file access problem. Please have also another look at the log.

If this does not help, can you clone this repo, execute `npm install`, build the extension locally and run it ("Launch Extension")?

<img width="648" alt="Screenshot 2021-01-24 at 19 43 38" src="https://user-images.githubusercontent.com/4279702/105640119-82e60380-5e7c-11eb-9f5e-fae408eb586b.png">

you can may try to log some things within the file `src/webview.ts`...

sorry that I can't help here better, but until know I wasn't able to find some problem or reproduce it.

**Comment by d-koppenhagen** [comment]
Hey @beyondverage0908 as you closed this issue, I assume, that the extension works now? If yes: can you please describe in short you you've been able to fix it?
