### ISSUE TITLE
[feature] Filter comments by commit

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#88]
# 🧩 Feature

## Description

When we are reviewing multiple branches of a same project at the same time, the comments get mixed (in the tree-view, in the export), making it difficult to distinguish them and to communicate with the rest of the team.

The capability of filtering the comments **based on the current commit ID** would solve this issue.  
In filtered mode:

- Only the wanted comments will be displayed in the tree-view.
- Only the wanted comments will be exported.

Switching from one commit to another with automatically refresh the list.
It will be possible to switch back to an all comments view at any time.

A pull request dedicated to this feature is coming soon.

**Comment by d-koppenhagen** [comment]
@michelcaradec thanks for your contribution. I just published Version 1.22.0 🎉
