### ISSUE TITLE
[bug] Can't add a new note

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#90]
# 🐞 Bug report

## Description

When adding a note, clicking on the "Add Note" button has no effect.

## Reproduction

1. Create a **new** note.
2. Add a description.
3. Click on the "Add Note" button. 

## Error message

When looking at the development console, the following message appears:

<pre><code>
mainThreadExtensionService.ts:65 [[object Object]]Cannot create property 'id' on string '{"sha":"","filename":"","url":"","lines":"","title":"Some title","comment":"Some description","priority":1,"category":"Suggestion","additional":"","private":1,"code":""}'
</code></pre>

## 🌍 Your Environment

<pre><code>
vscode-review Extension 1.22.0

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.0-051000-generic
</code></pre>

I will try to investigate as soon as possible.

**Comment by keesj-exset** [comment]
Hi,

I have also just given this tool a go and rand into similar issues. If I have a workspace open where I added multiple directories it looks like the code-review.csv is not created. I tried a second time (also linux) on a different project and now the file was created but still I can not add notes. cool project

**Comment by michelcaradec** [comment]
I did a quick first investigation.
I think I identified the problem: <https://github.com/d-koppenhagen/vscode-code-review/commit/9f53d87fcfae97364cf2fe978cf8769762536651#diff-6bfea2ec3c1d21c90d6e1ecd704f380a6eeb44521e1da1a87b6a48ea691b6a43>

The JSON.parse call `const comment = JSON.parse(object) as CsvEntry;` is necessary to make the object schema updatable (i.e. add the `id`property).

More investigations to come later.

**Comment by d-koppenhagen** [comment]
Hey, that's a strange behavior indeed.
I mainly made this code change because the extension tests were failing before which blocked the release.

**Comment by michelcaradec** [comment]
The header of the function `export function createCommentFromObject(object: any | CsvEntry): CsvEntry`is erroneous and confusing.
At the moment, it must receive a string.
I will rework it to accept any kind of representation (string, object).
