### ISSUE TITLE
[feature] Import comments

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#94]
# 🧩 Feature

## Description

When collaborating with a team of developers, it can be interesting to import theirs comments to consolidate them in a single place.
This is also a handy way to send a code review without using any platform such as Github.

Importing comments could be possible from a JSON file (the one generated by the export command of the extension), with the following conflict options:

- Keep the existing comments.
- Replace the existing comments with the imported ones.
- Keep the existing and imported comments.

The conflict detection will be based on the comment identifier added in #75 .

I started working on this feature, a pull request should hopefuly come in the next days.

**Comment by d-koppenhagen** [comment]
Great idea! Looking forward to review the PR!

**Comment by keesj-exset** [comment]
We have been working on a different approach in the past where code annotations are made in the code (in a different branch from the working code branch) and a diff is generated that creates the annotations. This allows for multiple users to create annotations and merge them (or even rebase them after code change) but overall while having some very nice properties is perhaps not as gui friendly as this extension. That said the code is only 300 lines of code so I can perhaps also make it compatible with this json format!. An alternative would be to allow multiple cvs files to be used?

https://github.com/x7-labs/git-code-annotate

**Comment by keesj-exset** [comment]
Hi,

* Keep the existing comments.
* Replace the existing comments with the imported ones.
* Keep the existing and imported comments.

It would be very valuable to have a 2 or 3 way diff type diff. The main reason being that the case above here do not always apply. Keep existing comments would not allow an other person to filter and remove comments (e.g. they find them invalid) it might be possible to add a category "invalid/deleted" so solve this issue. Replace existing comments: it is not clear what comment was there first, it would be very nice to see the two and choose/modify

Meld is pretty good at this type of merging specially when the file format is suitable. https://meldmerge.org/ but there must be an existing extension that already comes close.

**Comment by michelcaradec** [comment]
Hello @keesj-exset,
The implementation of the initial feature description is nearly completed (and under test on my environment), but I will think about adding a "merge" action, that will concatenate the description (or something like that, simple).
Thank you.
