### ISSUE TITLE
[feature] Enable Github Sponsors

### ISSUE THREAD

**Issue by tejpochiraju** [d-koppenhagen/vscode-code-review#97]
# 🧩 Feature
Enable Github Sponsors

## Description

I would love to support this plugin but BuyMeACoffee only works with Paypal which in turn doesn't really work/work consistently in India.

**Comment by d-koppenhagen** [comment]
Thanks for your support! Creating a Github Sponsors Profile was already on my ToDo-List. I will let you know once it's published.

**Comment by d-koppenhagen** [comment]
My Github Sponsors profile is now linked to this project. Thanks for your support!
