### ISSUE TITLE
[feature] Sync between gitlab merge request an the CR

### ISSUE THREAD

**Issue by katzimoto** [d-koppenhagen/vscode-code-review#99]
# 🧩 Feature
Today we are using gitlab merge request for CR, is it possible not to open an issue about every note but to add an a comment on the merge request?

**Comment by d-koppenhagen** [comment]
Hey I am not sure if I understood the use case. 
Your are using Gitlab and you want to make comments on Merge Requests based on comments zog created with this code review extension for a specific change set?
I think that's not a typical use case for this extension. Why aren't you making just review comments directly in the merge request?

So the main idea of this extension is to provide reviews / comments for code where there's not merge request / pull request or not repo at all: simply code.

**Comment by newag** [comment]
I would like to do my Cr on vscode where I can see the full context of the code, and to save the cr on the merge request so that the one who goes to fix the cr will be able to access my comments easily.

**Comment by d-koppenhagen** [comment]
I thinks this is not the scope of this extension. It's implementation would be very specific to the used Git-Tool (Github, Gitlab, Bitbucket, etc.). As far as I know, there isn't such feature to sync this. when opening a MR, a review can have a look at the commend in the checked-in `code-review.csv` file and solve the issues.

Until now, I will close this issue but I am open to be convinced from your Idea when you can define your concept / considerations and some source about how it can be implemented.
